import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInputTextSkeleton } from "./TypeInputText";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeMosaicModuleSkeleton } from "./TypeMosaicModule";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTooltipSkeleton } from "./TypeTooltip";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";
import type { TypeWarrantyPlanTextTooltipSkeleton } from "./TypeWarrantyPlanTextTooltip";
import type { TypeWeAcceptComponentSkeleton } from "./TypeWeAcceptComponent";

export interface TypeCartPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    isSingleton?: EntryFieldTypes.Symbol<"Yes">;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    selectFreeGiftButtonLabelSingular: EntryFieldTypes.Symbol;
    selectFreeGiftButtonLabelPlural: EntryFieldTypes.Symbol;
    changeFreeGiftButtonLabelSingular: EntryFieldTypes.Symbol;
    changeFreeGiftButtonLabelPlural: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpTitleSingular: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpTitlePlural: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpDescriptionSingular: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpDescriptionPlural: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpSummarySelectionLabelPlural: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpButtonCheckboxLabel: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpApplySelectionLabel: EntryFieldTypes.Symbol;
    selectFreeGiftPopUpSwitchGiftLabel: EntryFieldTypes.Symbol;
    weAcceptComponent: EntryFieldTypes.EntryLink<TypeWeAcceptComponentSkeleton>;
    checkoutNavigationLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    cartCountLabel: EntryFieldTypes.Symbol;
    cartCountPluralLabel: EntryFieldTypes.Symbol;
    giftWrappingTitleLabel: EntryFieldTypes.Symbol;
    giftWrappingOptionLabel: EntryFieldTypes.Symbol;
    promoCodeTitleLabel: EntryFieldTypes.Symbol;
    promoCodeInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    promoCodeTooltip?: EntryFieldTypes.EntryLink<TypeTooltipSkeleton>;
    warrantyPlanTextTooltip?: EntryFieldTypes.EntryLink<TypeWarrantyPlanTextTooltipSkeleton>;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeMosaicModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
}

export type TypeCartPageSkeleton = EntrySkeletonType<TypeCartPageFields, "cartPage">;
export type TypeCartPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeCartPageSkeleton, Modifiers, Locales>;
