import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeBadgeSkeleton } from "./TypeBadge";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeComparisonItemSkeleton } from "./TypeComparisonItem";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInsuranceFactorSkeleton } from "./TypeInsuranceFactor";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePersonalisationDynamicPicturesSkeleton } from "./TypePersonalisationDynamicPictures";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductDiscountSkeleton } from "./TypeProductDiscount";
import type { TypeProductFeatureSkeleton } from "./TypeProductFeature";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductItemSkeleton } from "./TypeProductItem";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductPersonalisationPictureSkeleton } from "./TypeProductPersonalisationPicture";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";
import type { TypeWarrantyPlanTextTooltipSkeleton } from "./TypeWarrantyPlanTextTooltip";

export interface TypeProductDetailPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    twelveNc?: EntryFieldTypes.Symbol;
    twelveNcOld?: EntryFieldTypes.Symbol;
    parentPartNumber?: EntryFieldTypes.Symbol;
    isBiggerTile?: EntryFieldTypes.Boolean;
    discount?: EntryFieldTypes.EntryLink<TypeProductDiscountSkeleton>;
    badge?: EntryFieldTypes.EntryLink<TypeBadgeSkeleton>;
    personalisationActive: EntryFieldTypes.Boolean;
    personalisationDetailLink?: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    instalmentLabelActive: EntryFieldTypes.Boolean;
    valueAddedTaxLabelActive: EntryFieldTypes.Boolean;
    insuranceFactors?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeInsuranceFactorSkeleton>>;
    warrantyPlanTextTooltip?: EntryFieldTypes.EntryLink<TypeWarrantyPlanTextTooltipSkeleton>;
    items?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeProductItemSkeleton>>;
    features?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeProductFeatureSkeleton>>;
    comparisonItems?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeComparisonItemSkeleton>>;
    personalisationDynamicPictures?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypePersonalisationDynamicPicturesSkeleton>>;
    defaultPersonalisationAttachmentPicture?: EntryFieldTypes.AssetLink;
    attachmentsPersonalisationPictures?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeProductPersonalisationPictureSkeleton>>;
    relatedProductsModule?: EntryFieldTypes.EntryLink<TypeRelatedProductsModuleSkeleton>;
    seeAllRelatedProductsLink?: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
}

export type TypeProductDetailPageSkeleton = EntrySkeletonType<TypeProductDetailPageFields, "productDetailPage">;
export type TypeProductDetailPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeProductDetailPageSkeleton, Modifiers, Locales>;
