import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeInputSelectSkeleton } from "./TypeInputSelect";
import type { TypeInputSelectValueSkeleton } from "./TypeInputSelectValue";
import type { TypeInputTextSkeleton } from "./TypeInputText";
import type { TypeInsuranceFactorSkeleton } from "./TypeInsuranceFactor";
import type { TypeMyAccountCommonSkeleton } from "./TypeMyAccountCommon";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";

export interface TypeAccountComponentFields {
    internalName: EntryFieldTypes.Symbol;
    anchorLinkId?: EntryFieldTypes.Symbol;
    isSingleton?: EntryFieldTypes.Symbol<"Yes">;
    signInTitle: EntryFieldTypes.Symbol;
    emailInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    passwordInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    firstNameInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    lastNameInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    professionalDiscountInput?: EntryFieldTypes.EntryLink<TypeInputSelectValueSkeleton>;
    signInLabel: EntryFieldTypes.Symbol;
    forgotPasswordTitleLabel: EntryFieldTypes.Symbol;
    sendLabel: EntryFieldTypes.Symbol;
    modifyPasswordTitleLabel: EntryFieldTypes.Symbol;
    modifyPasswordInfoTextLabel: EntryFieldTypes.Symbol;
    modifyPasswordButtonLabel: EntryFieldTypes.Symbol;
    forgotPasswordLabel: EntryFieldTypes.Symbol;
    createAccountTitle: EntryFieldTypes.Symbol;
    insurranceFactors: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeInsuranceFactorSkeleton>>;
    createAccountLabel: EntryFieldTypes.Symbol;
    currentPasswordInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    newPasswordInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    repeatPasswordInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    repeatEmailInput?: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    termsAndConditionInput: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    legalTextLabel?: EntryFieldTypes.RichText;
    optinNewsletterInput: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    optinProfilingInput?: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    backLabel: EntryFieldTypes.Symbol;
    registerLabel: EntryFieldTypes.Symbol;
    continueLabel: EntryFieldTypes.Symbol;
    codeInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    codeHelpText: EntryFieldTypes.Symbol;
    createAccountHelpText: EntryFieldTypes.Symbol;
    duplicatedAccountErrorMessage: EntryFieldTypes.Symbol;
    invalidCredentialsErrorMessage: EntryFieldTypes.Symbol;
    alreadySignedInErrorMessage: EntryFieldTypes.Symbol;
    notSignedInErrorMessage: EntryFieldTypes.Symbol;
    noAuthenticationSessionTokenErrorMessage: EntryFieldTypes.Symbol;
    noAccountProfileErrorMessage: EntryFieldTypes.Symbol;
    getMyAccountOrdersListFailureErrorMessage: EntryFieldTypes.Symbol;
    getRegisteredProductsFailureErrorMessage: EntryFieldTypes.Symbol;
    logRegisteredProductFailureErrorMessage: EntryFieldTypes.Symbol;
    orderNotFoundErrorMessage: EntryFieldTypes.Symbol;
    myAccountCommon: EntryFieldTypes.EntryLink<TypeMyAccountCommonSkeleton>;
    myAccountTitleLabel: EntryFieldTypes.Symbol;
    trackYourOrderLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    registerYourProductLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    logoutLabel: EntryFieldTypes.Symbol;
    forgotPasswordPageUrl?: EntryFieldTypes.Symbol;
    forgotPasswordDescription?: EntryFieldTypes.Symbol;
}

export type TypeAccountComponentSkeleton = EntrySkeletonType<TypeAccountComponentFields, "accountComponent">;
export type TypeAccountComponent<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeAccountComponentSkeleton, Modifiers, Locales>;
