import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAddressLabelsSkeleton } from "./TypeAddressLabels";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInputSelectSkeleton } from "./TypeInputSelect";
import type { TypeInputSelectValueSkeleton } from "./TypeInputSelectValue";
import type { TypeInputTextSkeleton } from "./TypeInputText";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeMosaicModuleSkeleton } from "./TypeMosaicModule";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePaymentMethodSkeleton } from "./TypePaymentMethod";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductReferenceModalModuleSkeleton } from "./TypeProductReferenceModalModule";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypeProfileLabelsSkeleton } from "./TypeProfileLabels";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";

export interface TypeCheckoutPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    isSingleton?: EntryFieldTypes.Symbol<"Yes">;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    stepList: EntryFieldTypes.Array<EntryFieldTypes.Symbol>;
    orLabel: EntryFieldTypes.Symbol;
    continueAsGuest: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    creditCardLabel: EntryFieldTypes.Symbol;
    orderTypeTitleLabel: EntryFieldTypes.Symbol;
    personalDetailTitleLabel: EntryFieldTypes.Symbol;
    deliveryAddressTitleLabel: EntryFieldTypes.Symbol;
    billingAddressTitleLabel: EntryFieldTypes.Symbol;
    sameAsDeliveryAddressLabel: EntryFieldTypes.Symbol;
    deliveryModeLabel: EntryFieldTypes.Symbol;
    deliveryModifyLabel: EntryFieldTypes.Symbol;
    continueToPaymentLabel: EntryFieldTypes.Symbol;
    confirmAndPayLabel: EntryFieldTypes.Symbol;
    yourInformationLabel: EntryFieldTypes.Symbol;
    validateChangeLabel: EntryFieldTypes.Symbol;
    modifyLabel: EntryFieldTypes.Symbol;
    saveLabel: EntryFieldTypes.Symbol;
    orderTypeInput: EntryFieldTypes.EntryLink<TypeInputSelectValueSkeleton>;
    companyInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    vatNumberInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    profileLabels: EntryFieldTypes.EntryLink<TypeProfileLabelsSkeleton>;
    addressLabels: EntryFieldTypes.EntryLink<TypeAddressLabelsSkeleton>;
    companyOrBuildingInput: EntryFieldTypes.EntryLink<TypeInputTextSkeleton>;
    useDistinctBillingAddressInput: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    termsAndConditionInput: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    legalText: EntryFieldTypes.RichText;
    optinNewsletterInput: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    optinProfilingInput?: EntryFieldTypes.EntryLink<TypeInputSelectSkeleton>;
    successPageLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    thankYouTitle: EntryFieldTypes.Symbol;
    thankYouText: EntryFieldTypes.Symbol;
    myContactInfoTitleLabel: EntryFieldTypes.Symbol;
    paymentTitleLabel: EntryFieldTypes.Symbol;
    deliveryDateLabel: EntryFieldTypes.Symbol;
    orderNumberLabel: EntryFieldTypes.Symbol;
    companyDetailLabel: EntryFieldTypes.Symbol;
    confirmationEmail: EntryFieldTypes.Symbol;
    popularFaqLabel: EntryFieldTypes.Symbol;
    paymentMethodLabel: EntryFieldTypes.Symbol;
    paymentMethods: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypePaymentMethodSkeleton>>;
    genericErrorMessage: EntryFieldTypes.Symbol;
    invalidCouponErrorMessage: EntryFieldTypes.Symbol;
    haveAccountLabel?: EntryFieldTypes.Symbol;
    signInHereLabel?: EntryFieldTypes.Symbol;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeMosaicModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductReferenceModalModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
    phoneNumberTooltip?: EntryFieldTypes.EntryLink<EntrySkeletonType>;
}

export type TypeCheckoutPageSkeleton = EntrySkeletonType<TypeCheckoutPageFields, "checkoutPage">;
export type TypeCheckoutPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeCheckoutPageSkeleton, Modifiers, Locales>;
