import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeCartPageSkeleton } from "./TypeCartPage";
import type { TypeCountdownSkeleton } from "./TypeCountdown";
import type { TypeDeliveryOptionSkeleton } from "./TypeDeliveryOption";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";

export interface TypeCartComponentFields {
    internalName: EntryFieldTypes.Symbol;
    anchorLinkId?: EntryFieldTypes.Symbol;
    isSingleton?: EntryFieldTypes.Symbol<"Yes">;
    emptyCartLabel: EntryFieldTypes.Symbol;
    emptyCartImage?: EntryFieldTypes.AssetLink;
    cartTitleLabel: EntryFieldTypes.Symbol;
    addedToCartLabel: EntryFieldTypes.Symbol;
    continueShoppingLabel: EntryFieldTypes.Symbol;
    cartItemQuantityLabel: EntryFieldTypes.Symbol;
    cartItemRemoveLabel: EntryFieldTypes.Symbol;
    productNotFoundOrUnvailableText: EntryFieldTypes.RichText;
    productQuantityUnavailableText: EntryFieldTypes.RichText;
    productMaxQuantityReachedText: EntryFieldTypes.RichText;
    giftWrappingWarningText: EntryFieldTypes.RichText;
    cartDefaultErrorText: EntryFieldTypes.RichText;
    deliverOptionsTitleLabel: EntryFieldTypes.Symbol;
    deliveryOptions: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeDeliveryOptionSkeleton>>;
    deliveryTimePromiseLabel?: EntryFieldTypes.Symbol;
    promoCodeAlreadyConsumedText: EntryFieldTypes.RichText;
    promoCodeNotActiveText: EntryFieldTypes.RichText;
    promoCodeNotCombinableText: EntryFieldTypes.RichText;
    promoCodeNotMatchingText: EntryFieldTypes.RichText;
    promoCodeNotFoundText: EntryFieldTypes.RichText;
    promoCodeNotApplicableText: EntryFieldTypes.RichText;
    promoNotFoundText: EntryFieldTypes.RichText;
    freeGiftNotFoundText: EntryFieldTypes.RichText;
    totalLabel: EntryFieldTypes.Symbol;
    subTotalLabel: EntryFieldTypes.Symbol;
    shippingLabel: EntryFieldTypes.Symbol;
    giftWrappingLabel: EntryFieldTypes.Symbol;
    discountLabel: EntryFieldTypes.Symbol;
    engravingLabel: EntryFieldTypes.Symbol;
    installmentLabel?: EntryFieldTypes.Symbol;
    installmentIcon?: EntryFieldTypes.AssetLink;
    freeLabel: EntryFieldTypes.Symbol;
    expressPaymentMethods?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>>;
    includeVatLabel: EntryFieldTypes.Symbol;
    myCartNavigationLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    youOrderLabel: EntryFieldTypes.Symbol;
    myOrderDetailLabel: EntryFieldTypes.Symbol;
    cartPage: EntryFieldTypes.EntryLink<TypeCartPageSkeleton>;
    addToCartPopupNavigationLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    addToCartPopupTitle: EntryFieldTypes.Symbol;
    relatedProductsModule?: EntryFieldTypes.EntryLink<TypeRelatedProductsModuleSkeleton>;
    productOutOfStockErrorMessage: EntryFieldTypes.Symbol;
    checkoutNavigationLink: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
    backInStockLabels?: EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton>;
    labels?: EntryFieldTypes.Object;
    countdown?: EntryFieldTypes.EntryLink<TypeCountdownSkeleton>;
}

export type TypeCartComponentSkeleton = EntrySkeletonType<TypeCartComponentFields, "cartComponent">;
export type TypeCartComponent<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeCartComponentSkeleton, Modifiers, Locales>;
