import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeAuthorSkeleton } from "./TypeAuthor";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeMosaicModuleSkeleton } from "./TypeMosaicModule";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductReferenceModalModuleSkeleton } from "./TypeProductReferenceModalModule";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";

export interface TypeBlogDetailPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    supportedLocales: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Austria_German" | "Belgium_Dutch" | "Belgium_French" | "Canada_English" | "Canada_French" | "Denmark_Danish" | "Finland_Finnish" | "France_French" | "Germany_German" | "Ireland_English" | "Italy_Italian" | "Netherlands_Dutch" | "Portugal_Portuguese" | "Spain_Spanish" | "Sweden_Swedish" | "Switzerland_French" | "Switzerland_German" | "Switzerland_Italian" | "UnitedKingdom_English" | "UnitedStates_English">>;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    author: EntryFieldTypes.EntryLink<TypeAuthorSkeleton>;
    readTimeLabel: EntryFieldTypes.Symbol;
    categories: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Insights" | "Inspirations" | "Tips">>;
    heroBannerImage: EntryFieldTypes.AssetLink;
    heroBannerVideoUrl?: EntryFieldTypes.Symbol;
    blogIntoText: EntryFieldTypes.RichText;
    anchorLinks: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>>;
    sections: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeRichTextModuleSkeleton>>;
    suggestedTools?: EntryFieldTypes.EntryLink<TypeRelatedProductsModuleSkeleton>;
    browseInTheseCategoriesModule: EntryFieldTypes.EntryLink<TypeNavigationLinkModuleSkeleton>;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeMosaicModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductReferenceModalModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
}

export type TypeBlogDetailPageSkeleton = EntrySkeletonType<TypeBlogDetailPageFields, "blogDetailPage">;
export type TypeBlogDetailPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeBlogDetailPageSkeleton, Modifiers, Locales>;
