import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeContentCardSkeleton } from "./TypeContentCard";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeMosaicModuleSkeleton } from "./TypeMosaicModule";
import type { TypeNavigationLinkSkeleton } from "./TypeNavigationLink";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductListingComponentLabelsSkeleton } from "./TypeProductListingComponentLabels";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductReferenceModalModuleSkeleton } from "./TypeProductReferenceModalModule";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";

export interface TypeCustomListingPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    collectionName?: EntryFieldTypes.Symbol;
    homeBanner?: EntryFieldTypes.EntryLink<TypeHomeBannerModuleSkeleton>;
    promoHomeBanner?: EntryFieldTypes.EntryLink<TypePromoHomeBannerModuleSkeleton>;
    heroModules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
    title?: EntryFieldTypes.Symbol;
    linkSlider?: EntryFieldTypes.EntryLink<TypeLinkSliderModuleSkeleton>;
    enableFacets?: EntryFieldTypes.Boolean;
    hidePromoBadges?: EntryFieldTypes.Boolean;
    labels: EntryFieldTypes.EntryLink<TypeProductListingComponentLabelsSkeleton>;
    contentCards?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeContentCardSkeleton>>;
    hiddenFacetClusters?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"BatteryIncluded" | "Batteryincluded(cordlessappliancesonly)" | "Capacity" | "CategoryOfProduct" | "CategoryOfSet" | "CoffeeType" | "Colour" | "CompatibleWith" | "CupServings" | "Guarantee" | "LevelOfDiscount" | "Price" | "SpecialOffer" | "Warranty" | "WaterCapacity">>;
    isColourPage?: EntryFieldTypes.Boolean;
    colour?: EntryFieldTypes.Symbol<"Agave" | "Almond cream" | "Apple cider" | "Azure blue" | "Beetroot" | "Blossom" | "Blue Salt" | "Blue agave" | "Blue velvet" | "Blueberry" | "Boysenberry" | "Brushed nickel" | "Café latte" | "Candy apple" | "Cast iron black" | "Champagne gold" | "Charcoal" | "Chrome" | "Contour silver" | "Copper" | "Coral" | "Cranberry" | "Crimson red" | "Crystal blue" | "Dark pewter" | "Dried rose" | "Electric blue" | "Empire red" | "Espresso" | "Evergreen" | "Feather pink" | "Fog blue" | "Fresh linen" | "Frosted pearl" | "Grape" | "Green apple" | "Grenadine" | "Guava glaze" | "Hibiscus" | "Honey" | "Honeydew" | "Hot sauce" | "Ice blue" | "Imperial grey" | "Ink blue" | "Juniper" | "Kyoto glow" | "Lavender cream" | "Light and shadow" | "Liquid graphite" | "Majestic yellow" | "Matcha" | "Matte black" | "Matte grey" | "Matte pistachio" | "Matte white" | "Medallion silver" | "Metallic chrome" | "Milkshake" | "Mineral water" | "Misty blue" | "Onyx black" | "Pebbled palm" | "Pink" | "Pistachio" | "Plumberry" | "Porcelain white" | "Porcelain" | "Raspberry ice" | "Sand" | "Sea glass" | "Silk pink" | "Silver" | "Slate" | "Starry night" | "Tangerine" | "Terracotta" | "Twilight blue" | "White" | "Yellow pepper">;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeMosaicModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductReferenceModalModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
    facetCta?: EntryFieldTypes.EntryLink<TypeNavigationLinkSkeleton>;
}

export type TypeCustomListingPageSkeleton = EntrySkeletonType<TypeCustomListingPageFields, "customListingPage">;
export type TypeCustomListingPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeCustomListingPageSkeleton, Modifiers, Locales>;
