import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
import type { TypeAlertSkeleton } from "./TypeAlert";
import type { TypeAuthorSkeleton } from "./TypeAuthor";
import type { TypeBackInStockLabelsSkeleton } from "./TypeBackInStockLabels";
import type { TypeBadgeSkeleton } from "./TypeBadge";
import type { TypeColorSkeleton } from "./TypeColor";
import type { TypeColumnContentWrapperModuleSkeleton } from "./TypeColumnContentWrapperModule";
import type { TypeContactUsModuleSkeleton } from "./TypeContactUsModule";
import type { TypeDisclaimerModuleSkeleton } from "./TypeDisclaimerModule";
import type { TypeFaqTooltipModuleSkeleton } from "./TypeFaqTooltipModule";
import type { TypeHeroBannerOverflowingModuleSkeleton } from "./TypeHeroBannerOverflowingModule";
import type { TypeHeroColumnBannerWrapperModuleSkeleton } from "./TypeHeroColumnBannerWrapperModule";
import type { TypeHomeBannerModuleSkeleton } from "./TypeHomeBannerModule";
import type { TypeInternalHeadingModuleSkeleton } from "./TypeInternalHeadingModule";
import type { TypeLinkSliderModuleSkeleton } from "./TypeLinkSliderModule";
import type { TypeMediaModuleSkeleton } from "./TypeMediaModule";
import type { TypeMediaReviewModuleSkeleton } from "./TypeMediaReviewModule";
import type { TypeModBlockListModuleSkeleton } from "./TypeModBlockListModule";
import type { TypeNavigationLinkModuleSkeleton } from "./TypeNavigationLinkModule";
import type { TypeNewsletterSubscriptionModuleSkeleton } from "./TypeNewsletterSubscriptionModule";
import type { TypePatchworkModuleSkeleton } from "./TypePatchworkModule";
import type { TypePhotoLeftRightModuleSkeleton } from "./TypePhotoLeftRightModule";
import type { TypePhotoWallModuleSkeleton } from "./TypePhotoWallModule";
import type { TypePopUpModuleSkeleton } from "./TypePopUpModule";
import type { TypeProductComparisonTableModuleSkeleton } from "./TypeProductComparisonTableModule";
import type { TypeProductFeaturesModuleSkeleton } from "./TypeProductFeaturesModule";
import type { TypeProductOverviewModuleSkeleton } from "./TypeProductOverviewModule";
import type { TypeProductReferenceModalModuleSkeleton } from "./TypeProductReferenceModalModule";
import type { TypeProductSpecificationModuleSkeleton } from "./TypeProductSpecificationModule";
import type { TypeProductWhatsInTheBoxModuleSkeleton } from "./TypeProductWhatsInTheBoxModule";
import type { TypePromoBannerModuleSkeleton } from "./TypePromoBannerModule";
import type { TypePromoHomeBannerModuleSkeleton } from "./TypePromoHomeBannerModule";
import type { TypeQuoteModuleSkeleton } from "./TypeQuoteModule";
import type { TypeReadMoreModuleSkeleton } from "./TypeReadMoreModule";
import type { TypeRecipeDetailPageLabelsSkeleton } from "./TypeRecipeDetailPageLabels";
import type { TypeRecipeStepSkeleton } from "./TypeRecipeStep";
import type { TypeRelatedContentsModuleSkeleton } from "./TypeRelatedContentsModule";
import type { TypeRelatedProductsModuleSkeleton } from "./TypeRelatedProductsModule";
import type { TypeRichTextModuleSkeleton } from "./TypeRichTextModule";
import type { TypeScriptCodeModuleSkeleton } from "./TypeScriptCodeModule";
import type { TypeSearchModuleSkeleton } from "./TypeSearchModule";
import type { TypeTrackMyOrderModuleSkeleton } from "./TypeTrackMyOrderModule";

export interface TypeRecipeDetailPageFields {
    name: EntryFieldTypes.Symbol;
    internalName: EntryFieldTypes.Symbol;
    supportedLocales: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Austria_German" | "Belgium_Dutch" | "Belgium_French" | "Canada_English" | "Canada_French" | "Denmark_Danish" | "Finland_Finnish" | "France_French" | "Germany_German" | "Ireland_English" | "Italy_Italian" | "Netherlands_Dutch" | "Portugal_Portuguese" | "Spain_Spanish" | "Sweden_Swedish" | "Switzerland_French" | "Switzerland_German" | "Switzerland_Italian" | "UnitedKingdom_English" | "UnitedStates_English">>;
    alerts?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeAlertSkeleton>>;
    recipeDetailPageLabels: EntryFieldTypes.EntryLink<TypeRecipeDetailPageLabelsSkeleton>;
    backgroundColor?: EntryFieldTypes.EntryLink<TypeColorSkeleton>;
    image: EntryFieldTypes.AssetLink;
    videoUrl?: EntryFieldTypes.Symbol;
    introText: EntryFieldTypes.RichText;
    badge?: EntryFieldTypes.EntryLink<TypeBadgeSkeleton>;
    author: EntryFieldTypes.EntryLink<TypeAuthorSkeleton>;
    courses: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Amusebouche" | "Bakery" | "Breakfast" | "Chips" | "Cold" | "Desserts" | "Dips" | "Dressing" | "Drinks" | "Fish" | "Hot" | "Maincourse" | "Meat" | "Pasta" | "Poultry" | "Sauces" | "Sides" | "Streetfood" | "Vegetarian">>;
    difficulty: EntryFieldTypes.Symbol<"Difficult" | "Easy" | "Intermediate">;
    cookingTime?: EntryFieldTypes.Integer;
    preparationTime?: EntryFieldTypes.Integer;
    settingTime?: EntryFieldTypes.Integer;
    restTime?: EntryFieldTypes.Integer;
    totalTime?: EntryFieldTypes.Integer;
    tools?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Blender" | "CoffeeMachine" | "CookProcessor" | "FoodProcessor" | "HandBlender" | "HandMixer" | "Kettle" | "StandMixer" | "Toaster">>;
    attachments?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"BreadBowl" | "CookiePress" | "FoodProcessorAttachment" | "FoodStrainer" | "GrainMill" | "IceCreamMaker" | "IceShaver" | "Juicer" | "MeatGrinder" | "OrangeJuicer" | "PastaCutters" | "PastaPress" | "PastaRoller" | "SausageStuffer" | "SheetCutter" | "Sifter" | "SlowJuicer" | "Spiralizer" | "VegetableSlicerAndShredder">>;
    seasonAndEvents?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"Fall" | "Festivities" | "Spring" | "Summer" | "Winter">>;
    specific?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"GlutenFree" | "LactoseFree" | "Vegan" | "Vegetarian">>;
    inspiration?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"AmericanCuisine" | "AsianCuisine" | "ComfortFood" | "EnglishCuisine" | "FrenchCuisine" | "HealtyAndFresh" | "InternationalCuisine" | "ItalianCuisine" | "Kids" | "LatinAmericanCuisine" | "MiddleEastCuisine" | "QuickAndEasy">>;
    serving: EntryFieldTypes.Integer;
    ingredients: EntryFieldTypes.Object;
    suggestedTools?: EntryFieldTypes.EntryLink<TypeRelatedProductsModuleSkeleton>;
    steps: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeRecipeStepSkeleton>>;
    anchorNavigationLinksModule?: EntryFieldTypes.EntryLink<TypeNavigationLinkModuleSkeleton>;
    quote?: EntryFieldTypes.Symbol;
    quoteAuthor?: EntryFieldTypes.Symbol;
    browsebyCategoryNavigationLinksModule?: EntryFieldTypes.EntryLink<TypeNavigationLinkModuleSkeleton>;
    sandwatchID?: EntryFieldTypes.Symbol;
    modules?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeBackInStockLabelsSkeleton | TypeColumnContentWrapperModuleSkeleton | TypeContactUsModuleSkeleton | TypeDisclaimerModuleSkeleton | TypeFaqTooltipModuleSkeleton | TypeHeroBannerOverflowingModuleSkeleton | TypeHeroColumnBannerWrapperModuleSkeleton | TypeHomeBannerModuleSkeleton | TypeInternalHeadingModuleSkeleton | TypeLinkSliderModuleSkeleton | TypeMediaModuleSkeleton | TypeMediaReviewModuleSkeleton | TypeModBlockListModuleSkeleton | TypeNavigationLinkModuleSkeleton | TypeNewsletterSubscriptionModuleSkeleton | TypePatchworkModuleSkeleton | TypePhotoLeftRightModuleSkeleton | TypePhotoWallModuleSkeleton | TypePopUpModuleSkeleton | TypeProductComparisonTableModuleSkeleton | TypeProductFeaturesModuleSkeleton | TypeProductOverviewModuleSkeleton | TypeProductReferenceModalModuleSkeleton | TypeProductSpecificationModuleSkeleton | TypeProductWhatsInTheBoxModuleSkeleton | TypePromoBannerModuleSkeleton | TypePromoHomeBannerModuleSkeleton | TypeQuoteModuleSkeleton | TypeReadMoreModuleSkeleton | TypeRelatedContentsModuleSkeleton | TypeRelatedProductsModuleSkeleton | TypeRichTextModuleSkeleton | TypeScriptCodeModuleSkeleton | TypeSearchModuleSkeleton | TypeTrackMyOrderModuleSkeleton>>;
}

export type TypeRecipeDetailPageSkeleton = EntrySkeletonType<TypeRecipeDetailPageFields, "recipeDetailPage">;
export type TypeRecipeDetailPage<Modifiers extends ChainModifiers, Locales extends LocaleCode = LocaleCode> = Entry<TypeRecipeDetailPageSkeleton, Modifiers, Locales>;
